# Generated by Django 5.2.4 on 2025-07-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_is_sale_product_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.BooleanField(default=False, help_text='True if product is sold out'),
        ),
    ]
